global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: redis_exporters
    static_configs:
      - targets:
          - redis-exporter-1:9121
          - redis-exporter-2:9121
          - redis-exporter-3:9121
          - redis-exporter-4:9121
          - redis-exporter-5:9121
          - redis-exporter-6:9121
